name: CI Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: List files in workspace for debugging
      run: ls -la
      working-directory: ${{ github.workspace }}

    - name: Set up Docker Compose
      run: |
        if ! command -v docker-compose &> /dev/null
        then
            echo "docker-compose not found, installing..."
            sudo apt-get update
            sudo apt-get install -y docker-compose
        else
            echo "docker-compose is already installed."
        fi
        docker-compose version
        docker version

    - name: Build and start Docker containers and wait for them to be ready (using 'docker compose')
      run: docker compose up -d --build --wait

    - name: Wait for Docker services to be ready (optional, but good practice)
      run: sleep 10 # Give services some time to fully start

    - name: List contents of /app in Docker container
      run: docker compose exec -t app-dev bash -c "ls -la /app"

    - name: Run tests inside Docker container
      run: docker compose exec -t app-dev bash -c "./gradlew test"